### ISSUE TITLE
Hey I want this too!

### ISSUE THREAD

**Issue by aphillipo** [techgaun/zxcvbn-elixir#1]
Let's collaborate?

**Comment by techgaun** [comment]
Hey @aphillipo sorry for the delay. I've added you as the collaborator. However, I don't have immediate timeline to start working on this. It might not be until the beginning of March until I start putting some stuff here. We can basically create a new org or move the somewhere else in the future. For now, I've invited you as collaborator. Lmk what your thoughts are and we can move forward together.

**Comment by aphillipo** [comment]
Let’s get the data in here and being read in by Elixir.

**Comment by aphillipo** [comment]
I’ll come up with a plan for different things we can do.

**Comment by techgaun** [comment]
I am closing this for now. I aim to get initial version by 3/20

**Comment by techgaun** [comment]
@aphillipo I've an initial version of this if you are interesed to look
