### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by axelson** [techgaun/zxcvbn-elixir#23]
Hi there 👋!

It would be greatly appreciated if a new release could be cut that includes some of the dep updates that are in `main` (and selfishly also my PR to fix compilation warnings on newer versions of Elixir #22)

**Comment by techgaun** [comment]
sure, I'll get a release out. thanks for the fixes

**Comment by axelson** [comment]
Great, thank you!

**Comment by techgaun** [comment]
ran into some bumps while publishing related to (dev) dependencies. I didn't have as much time to focus on this. Plan to do this over the weekend. Sorry for the delay.

**Comment by techgaun** [comment]
Went ahead and published https://hex.pm/packages/zxcvbn/0.2.0 . Appreciate your patience

**Comment by axelson** [comment]
Awesome, thank you! I've just published https://hex.pm/packages/password_validator_zxcvbn with zxcvbn 0.2.0 🎉

**Comment by techgaun** [comment]
probably a good idea for me to link to your package in the readme at some point. will do when I'm working at some point this week. thanks!
