### ISSUE TITLE
v0.2.0 Changelog entry

### ISSUE THREAD

**Issue by esambo** [techgaun/zxcvbn-elixir#24]
Thanks for releasing a new version.
It would be awesome if you could also please add an entry to the Changelog describing what was [included](https://github.com/techgaun/zxcvbn-elixir/compare/a147036eddcd26b37fc27e50b1194878d5c66d65...9b5bd8c8d5790b67f6aa33dc4ca84717e7cde558) in that new version.

**Comment by techgaun** [comment]
thanks @esambo for heads-up. how is https://github.com/techgaun/zxcvbn-elixir/blob/master/CHANGELOG.md looking now?
